package view;

import controller.Controleur;
import global.Configuration;

import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ludov
 */
public class Frames extends javax.swing.JFrame {
  /**
   * Creates new form
   */
  Controleur control;
  Images imgs;

  public Frames(Controleur c) {
    control = c;
    imgs = new Images();
    initComponents();
    setupBoutons();
    setupPanel();
    control.getInterface(this);
  }

  private void setupBoutons() {
    //menuPanel
    donnerAction(continuer, "continuer");
    donnerAction(charger, "charger");
    donnerAction(classement, "classement");
    donnerAction(credits, "credits");
    donnerAction(options, "options");
    donnerAction(quitter, "quitter");
    donnerAction(humainHumain, "vsHumain");
    donnerAction(humainMachine, "vsBot");
    donnerAction(regles, "regles");
    // optionsPanel
    donnerAction(retourOptions, "retourMP");
    // reglesPanel
    donnerAction(retourRegles, "retourMP");
    // creditsPanel
    donnerAction(retourCredits, "retourMP");

  }

  private void setupPanel() {
    menuPrincipale();
  }

  public void display() {
    System.out.println("display");
  }

  public void donnerAction(JButton b, String actionCommand) {
    b.setActionCommand(actionCommand);
    b.addActionListener(control);
  }

  public void menuPrincipale() {
    menuPrincipale.setVisible(true);
    menuCredits.setVisible(false);
    reglesPanel.setVisible(false);
    menuOptions.setVisible(false);
    plateauJeu.setVisible(false);
    quitterOptionPane.setVisible(false);
  }

  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menuPrincipale = new javax.swing.JPanel();
        Background = new Background();
        version = new javax.swing.JLabel();
        continuer = new javax.swing.JButton();
        charger = new javax.swing.JButton();
        humainMachine = new javax.swing.JButton();
        humainHumain = new javax.swing.JButton();
        credits = new javax.swing.JButton();
        options = new javax.swing.JButton();
        quitter = new javax.swing.JButton();
        regles = new javax.swing.JButton();
        classement = new javax.swing.JButton();
        quitterOptionPane = new javax.swing.JOptionPane();
        plateauJeu = new javax.swing.JPanel();
        plateauJeuScroll = new javax.swing.JScrollPane();
        menuOptions = new javax.swing.JPanel();
        optionsLabel = new javax.swing.JLabel();
        retourOptions = new javax.swing.JButton();
        menuCredits = new javax.swing.JPanel();
        creditsLabel = new javax.swing.JLabel();
        retourCredits = new javax.swing.JButton();
        creditsTextArea = new javax.swing.JTextArea();
        reglesPanel = new javax.swing.JPanel();
        retourRegles = new javax.swing.JButton();
        reglesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carcassonne");
        setIconImages(null);

        menuPrincipale.setPreferredSize(new java.awt.Dimension(1920, 1080));

        version.setText(Configuration.instance().lis("Version"));

        continuer.setText("Continuer");

        charger.setText("Charger");

        humainMachine.setText("1 VS IA");

        humainHumain.setText("1 VS 1");

        credits.setText("Credits");

        options.setText("Options");

        quitter.setText("Quitter");

        regles.setText("Règles");

        classement.setText("Classement");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(humainMachine, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(humainHumain, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(continuer, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(charger, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 841, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quitter, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(options, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(credits, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(regles, javax.swing.GroupLayout.Alignment.TRAILING,
                            javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                .addGap(0, 891, Short.MAX_VALUE)
                                .addComponent(classement, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(version)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())));
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                    .addContainerGap(328, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                            .addComponent(regles)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(credits))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                            .addComponent(continuer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(charger)
                            .addGap(12, 12, 12)
                            .addComponent(humainMachine)
                            .addGap(13, 13, 13)
                            .addComponent(humainHumain)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(options)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(quitter)
                    .addContainerGap())
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(classement)
                        .addGap(47, 47, 47)
                        .addComponent(version)
                        .addContainerGap(440, Short.MAX_VALUE))));

        /*javax.swing.GroupLayout menuPrincipaleLayout = new javax.swing.GroupLayout(menuPrincipale);
        menuPrincipale.setLayout(menuPrincipaleLayout);
        menuPrincipaleLayout.setHorizontalGroup(
            menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipaleLayout.createSequentialGroup()
                .addGroup(menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPrincipaleLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(humainHumain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(humainMachine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(version)
                            .addComponent(continuer, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(charger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPrincipaleLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(credits, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(regles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(menuPrincipaleLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(quitterOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 465, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPrincipaleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(quitter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(options, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        menuPrincipaleLayout.setVerticalGroup(
            menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classement)
                .addGroup(menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPrincipaleLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(version)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addComponent(quitterOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPrincipaleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continuer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(charger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(humainMachine)
                    .addComponent(regles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(humainHumain)
                    .addComponent(credits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(options)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quitter)
                .addContainerGap())
        );*/
        javax.swing.GroupLayout menuPrincipaleLayout = new javax.swing.GroupLayout(menuPrincipale);
        menuPrincipale.setLayout(menuPrincipaleLayout);
        menuPrincipaleLayout.setHorizontalGroup(
        menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        menuPrincipaleLayout.setVerticalGroup(
        menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

        plateauJeu.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout plateauJeuLayout = new javax.swing.GroupLayout(plateauJeu);
        plateauJeu.setLayout(plateauJeuLayout);
        plateauJeuLayout.setHorizontalGroup(
            plateauJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plateauJeuScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        plateauJeuLayout.setVerticalGroup(
            plateauJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plateauJeuScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        menuOptions.setPreferredSize(new java.awt.Dimension(1173, 568));
        menuOptions.setRequestFocusEnabled(false);

        optionsLabel.setText("Options");

        retourOptions.setText("Retour");

        javax.swing.GroupLayout menuOptionsLayout = new javax.swing.GroupLayout(menuOptions);
        menuOptions.setLayout(menuOptionsLayout);
        menuOptionsLayout.setHorizontalGroup(
            menuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOptionsLayout.createSequentialGroup()
                .addComponent(optionsLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuOptionsLayout.createSequentialGroup()
                .addContainerGap(1065, Short.MAX_VALUE)
                .addComponent(retourOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuOptionsLayout.setVerticalGroup(
            menuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOptionsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(optionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(retourOptions)
                .addContainerGap())
        );

        creditsLabel.setText("Crédits");

        retourCredits.setText("Retour");

        creditsTextArea.setColumns(20);
        creditsTextArea.setRows(5);
        creditsTextArea.setText("\n                           \n                          LOUBEAU Ludovic\n                        BERTRAMOND Camille\n                          KETTENIS Soteris\n                          FERREIRA Alexis\n                        BERENGUIER Lucas\n                          BELLIER Benjamin");
        creditsTextArea.setAutoscrolls(false);
        creditsTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        creditsTextArea.setFocusable(false);

        javax.swing.GroupLayout menuCreditsLayout = new javax.swing.GroupLayout(menuCredits);
        menuCredits.setLayout(menuCreditsLayout);
        menuCreditsLayout.setHorizontalGroup(
            menuCreditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCreditsLayout.createSequentialGroup()
                .addComponent(creditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuCreditsLayout.createSequentialGroup()
                .addContainerGap(863, Short.MAX_VALUE)
                .addComponent(retourCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuCreditsLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(creditsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuCreditsLayout.setVerticalGroup(
            menuCreditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCreditsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(creditsLabel)
                .addGap(114, 114, 114)
                .addComponent(creditsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(retourCredits)
                .addContainerGap())
        );

        retourRegles.setText("Retour");

        reglesLabel.setText("Régles");

        javax.swing.GroupLayout reglesPanelLayout = new javax.swing.GroupLayout(reglesPanel);
        reglesPanel.setLayout(reglesPanelLayout);
        reglesPanelLayout.setHorizontalGroup(
            reglesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reglesPanelLayout.createSequentialGroup()
                .addContainerGap(730, Short.MAX_VALUE)
                .addComponent(retourRegles, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(reglesPanelLayout.createSequentialGroup()
                .addComponent(reglesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        reglesPanelLayout.setVerticalGroup(
            reglesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reglesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(reglesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(retourRegles)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipale, javax.swing.GroupLayout.DEFAULT_SIZE, 1494, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plateauJeu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1494, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menuOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 268, Short.MAX_VALUE)
                    .addComponent(menuCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 269, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(reglesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipale, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plateauJeu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menuOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(menuCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(223, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(reglesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPrincipale.getAccessibleContext().setAccessibleName("menuPanel");

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify   
    private Background Background;                  
    private javax.swing.JButton charger;
    private javax.swing.JButton classement;
    private javax.swing.JButton continuer;
    private javax.swing.JButton credits;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JTextArea creditsTextArea;
    private javax.swing.JButton humainHumain;
    private javax.swing.JButton humainMachine;
    public javax.swing.JPanel menuCredits;
    public javax.swing.JPanel menuOptions;
    public javax.swing.JPanel menuPrincipale;
    private javax.swing.JButton options;
    private javax.swing.JLabel optionsLabel;
    public javax.swing.JPanel plateauJeu;
    private javax.swing.JScrollPane plateauJeuScroll;
    private javax.swing.JButton quitter;
    public javax.swing.JOptionPane quitterOptionPane;
    private javax.swing.JButton regles;
    private javax.swing.JLabel reglesLabel;
    public javax.swing.JPanel reglesPanel;
    private javax.swing.JButton retourCredits;
    private javax.swing.JButton retourOptions;
    private javax.swing.JButton retourRegles;
    private javax.swing.JLabel version;
    // End of variables declaration                   

}
