package view;

import controller.Controleur;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ludov
 */
public class Frames extends javax.swing.JFrame {
  /**
   * Creates new form
   */
  Controleur control;
  Images imgs;

  public Frames(Controleur c) {
    control = c;
    imgs = new Images();
    initComponents();
    setupBoutons();
    setupPanel();
    control.getInterface(this);
  }

  private void setupBoutons() {
    // menuPanel
    donnerAction(continuer, "continuer");
    donnerAction(charger, "charger");
    donnerAction(classement, "classement");
    donnerAction(credits, "credits");
    donnerAction(options, "options");
    donnerAction(quitter, "quitter");
    donnerAction(humainHumain, "vsHumain");
    donnerAction(humainMachine, "vsBot");
    donnerAction(regles, "regles");
    // optionsPanel
    donnerAction(retour, "retourMP");
    // reglesPanel
    donnerAction(retour, "retourMP");
    // creditsPanel
    donnerAction(retour, "retourMP");

  }

  private void setupPanel() {
    menuPrincipale();

    // menuPanel.setVisible(true);
    // creditsPanel.setVisible(false);
    // reglesPanel.setVisible(false);
    // optionsPanel.setVisible(false);
    // plateauJeuPanel.setVisible(false);
    // quitterOptionPane.setVisible(false);

  }

  public void display() {
    System.out.println("display");
  }

  public void donnerAction(JButton b, String actionCommand) {
    b.setActionCommand(actionCommand);
    b.addActionListener(control);
  }

  public void menuPrincipale() {
    menuPrincipale.setVisible(true);
    choixDeuxJoueurs.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    menuPrincipale = new javax.swing.JPanel();
    Background = new Background();
    continuer = new javax.swing.JButton();
    charger = new javax.swing.JButton();
    humainMachine = new javax.swing.JButton();
    humainHumain = new javax.swing.JButton();
    quitter = new javax.swing.JButton();
    options = new javax.swing.JButton();
    credits = new javax.swing.JButton();
    regles = new javax.swing.JButton();
    classement = new javax.swing.JButton();
    version = new javax.swing.JLabel();
    choixDeuxJoueurs = new javax.swing.JPanel();
    retour = new javax.swing.JButton();
    local = new javax.swing.JButton();
    reseau = new javax.swing.JButton();
    modeDeJeu = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Carcasonne");
    setIconImages(null);

    continuer.setText("Continuer");

    charger.setText("Charger");

    humainMachine.setText("1 VS IA");

    humainHumain.setText("1 VS 1");

    quitter.setText("Quitter");

    options.setText("Options");

    credits.setText("Credits");
    // credits.addActionListener(new java.awt.event.ActionListener() {
    //   public void actionPerformed(java.awt.event.ActionEvent evt) {
    //     creditsActionPerformed(evt);
    //   }
    // });

    regles.setText("Règles");
    // regles.addActionListener(new java.awt.event.ActionListener() {
    //   public void actionPerformed(java.awt.event.ActionEvent evt) {
    //     reglesActionPerformed(evt);
    //   }
    // });

    classement.setText("Classement");

    version.setText("Version : 0.0.0");

    javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
    Background.setLayout(BackgroundLayout);
    BackgroundLayout.setHorizontalGroup(
        BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(classement, javax.swing.GroupLayout.Alignment.TRAILING,
                            javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BackgroundLayout.createSequentialGroup()
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BackgroundLayout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(humainMachine, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(humainHumain, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(continuer, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(charger, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(431, 841, Short.MAX_VALUE)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                    BackgroundLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(quitter, javax.swing.GroupLayout.Alignment.TRAILING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(options, javax.swing.GroupLayout.Alignment.TRAILING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(credits, javax.swing.GroupLayout.Alignment.TRAILING,
                                            javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(regles, javax.swing.GroupLayout.Alignment.TRAILING,
                                    javax.swing.GroupLayout.PREFERRED_SIZE, 77,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(BackgroundLayout.createSequentialGroup()
                            .addComponent(version)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())));
    BackgroundLayout.setVerticalGroup(
        BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(classement)
                    .addGap(47, 47, 47)
                    .addComponent(version)
                    .addGap(147, 147, 147)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                            .addComponent(continuer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(charger)
                            .addGap(12, 12, 12)
                            .addComponent(humainMachine)
                            .addGap(13, 13, 13)
                            .addComponent(humainHumain)
                            .addGap(29, 29, 29))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                            .addComponent(regles)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(credits)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(options)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(quitter)))
                    .addContainerGap(135, Short.MAX_VALUE))));

    javax.swing.GroupLayout menuPrincipaleLayout = new javax.swing.GroupLayout(menuPrincipale);
    menuPrincipale.setLayout(menuPrincipaleLayout);
    menuPrincipaleLayout.setHorizontalGroup(
        menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    menuPrincipaleLayout.setVerticalGroup(
        menuPrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    retour.setText("Retour");
    // retour.addActionListener(new java.awt.event.ActionListener() {
    //   public void actionPerformed(java.awt.event.ActionEvent evt) {
    //     retourActionPerformed(evt);
    //   }
    // });

    local.setText("Local");

    reseau.setText("Réseau");

    modeDeJeu.setText("Mode de Jeu");

    javax.swing.GroupLayout choixDeuxJoueursLayout = new javax.swing.GroupLayout(choixDeuxJoueurs);
    choixDeuxJoueurs.setLayout(choixDeuxJoueursLayout);
    choixDeuxJoueursLayout.setHorizontalGroup(
        choixDeuxJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choixDeuxJoueursLayout.createSequentialGroup()
                .addGroup(choixDeuxJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(choixDeuxJoueursLayout.createSequentialGroup()
                        .addGroup(choixDeuxJoueursLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(choixDeuxJoueursLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modeDeJeu))
                            .addGroup(choixDeuxJoueursLayout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addGroup(choixDeuxJoueursLayout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reseau, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                                    .addComponent(local, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(318, 318, 318))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        choixDeuxJoueursLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap()));
    choixDeuxJoueursLayout.setVerticalGroup(
        choixDeuxJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choixDeuxJoueursLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(modeDeJeu)
                .addGap(99, 99, 99)
                .addComponent(local, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(54, 54, 54)
                .addComponent(reseau, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(114, 114, 114)
                .addComponent(retour)
                .addContainerGap()));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(choixDeuxJoueurs, javax.swing.GroupLayout.Alignment.TRAILING,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(choixDeuxJoueurs, javax.swing.GroupLayout.Alignment.TRAILING,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    getAccessibleContext().setAccessibleName("");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private Background Background;
  private javax.swing.JButton charger;
  private javax.swing.JPanel choixDeuxJoueurs;
  private javax.swing.JButton classement;
  private javax.swing.JButton continuer;
  private javax.swing.JButton credits;
  private javax.swing.JButton humainHumain;
  private javax.swing.JButton humainMachine;
  private javax.swing.JButton local;
  private javax.swing.JPanel menuPrincipale;
  private javax.swing.JLabel modeDeJeu;
  private javax.swing.JButton options;
  private javax.swing.JButton quitter;
  private javax.swing.JButton regles;
  private javax.swing.JButton reseau;
  private javax.swing.JButton retour;
  private javax.swing.JLabel version;
  // End of variables declaration//GEN-END:variables

}
